apiVersion: apps/v1
kind: Deployment
metadata:
  name: directus
  labels:
    app: directus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: directus
  template:
    metadata:
      labels:
        app: directus
    spec:
      containers:
      - name: directus
        image: directus/directus:11
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8055
        envFrom:
        - secretRef:
            name: uni-market-secrets
        volumeMounts:
        - name: directus-storage
          mountPath: /data
      imagePullSecrets:
        - name: compunet-3-secret
      volumes:
      - name: directus-storage
        persistentVolumeClaim:
          claimName: directus-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: directus-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: directus-service
spec:
  type: LoadBalancer
  loadBalancerIP: 35.237.238.109
  selector:
    app: directus
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8055
